services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ThisIsNotAPassword
    command: ["postgres", "-c", "log_statement=all"]
