name: sff-vektor
description: Showing the way in Science Fiction & Fantasy novels
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: ovh-typescript
packages:
  neon:
    source: terraform-provider
    version: 0.14.0
    parameters:
      - kislerdm/neon
      - 0.9.0
